'use client';
import { useEffect,useRef,useState } from 'react';
import { Camera,ImagePlus,X,Check } from 'lucide-react';
import { ErrorBox } from './Common';
export default function QrInput({value,onChange,disabled=false}:{value:string;onChange:(value:string)=>void;disabled?:boolean}){
  const [scanning,setScanning]=useState(false),[error,setError]=useState(''),[reading,setReading]=useState(false),[scanned,setScanned]=useState(false);
  const video=useRef<HTMLVideoElement>(null);const handler=useRef(onChange);handler.current=onChange;
  useEffect(()=>{if(!scanning)return;let cancelled=false;let stop:(()=>void)|undefined;const preview=video.current;
    void (async()=>{try{if(!navigator.mediaDevices?.getUserMedia)throw new Error('Camera unavailable. Use a QR photo or type the student ID below.');const {BrowserQRCodeReader}=await import('@zxing/browser');if(cancelled||!preview)return;const reader=new BrowserQRCodeReader();const controls=await reader.decodeFromConstraints({video:{facingMode:{ideal:'environment'}},audio:false},preview,(result,_error,controls)=>{if(result&&!cancelled){handler.current(result.getText());setScanned(true);controls.stop();setScanning(false);}});stop=()=>controls.stop();if(cancelled)controls.stop();}catch(e){if(!cancelled){setError(e instanceof Error&&e.name==='NotAllowedError'?'Camera permission was denied. Use a photo or type the student ID.':e instanceof Error?e.message:'Camera unavailable. Type the student ID manually.');setScanning(false);}}})();
    return()=>{cancelled=true;stop?.();const stream=preview?.srcObject;if(stream instanceof MediaStream)stream.getTracks().forEach(t=>t.stop());};
  },[scanning]);
  async function readImage(file?:File){if(!file)return;setReading(true);setError('');if(file.size>5*1024*1024){setError('Choose an image smaller than 5 MB.');setReading(false);return;}const url=URL.createObjectURL(file);try{const {BrowserQRCodeReader}=await import('@zxing/browser');const result=await new BrowserQRCodeReader().decodeFromImageUrl(url);onChange(result.getText());setScanned(true);}catch{setError('No readable QR was found in this photo. Try a clearer crop or type the student ID.');}finally{URL.revokeObjectURL(url);setReading(false);}}
  return <div className="kh-qr-input"><div className="rv-actions"><button type="button" className="rv-button" disabled={disabled||reading||scanning} onClick={()=>{setError('');setScanning(true);}}><Camera size={17}/>Scan college ID</button><label className="rv-button kh-file-button"><ImagePlus size={17}/>{reading?'Reading QR…':'Use QR photo'}<input aria-label="Choose QR photo" type="file" accept="image/png,image/jpeg,image/webp" disabled={disabled||reading||scanning} onChange={e=>void readImage(e.target.files?.[0])}/></label></div>{scanning&&<div className="kh-camera"><video ref={video} playsInline muted/><button type="button" className="rv-button" onClick={()=>setScanning(false)}><X size={15}/>Stop camera</button><p>Point the camera at the QR on the college ID.</p></div>}<label className="rv-field">OR TYPE THE STUDENT ID<input aria-label="College student ID" autoComplete="off" spellCheck={false} value={value} onChange={e=>{onChange(e.target.value);setScanned(false);}} placeholder="Student ID / USN on the college ID" maxLength={512} required disabled={disabled}/></label>{scanned&&<p className="kh-small-success"><Check size={15}/>QR read. Continue to check this ID.</p>}<p className="rv-helper">QR photos are read on this device. The photo is not uploaded.</p><ErrorBox message={error}/></div>;
}
