/**
 * KHOJ — Candidate Matches Repository
 * Manages candidate scorecards generated by the matching engine.
 *
 * CRITICAL PRODUCT PRINCIPLE:
 * A candidate match is an evidence scorecard, NEVER an automated ownership decision.
 * Scorecards must be protected from public tampering and leaks.
 */

import { id, now, one, all, run, transaction } from "@/lib/rvu/db";
import type { CandidateScoreCard, ProtectedItem, Report } from "@/lib/rvu/types";
import { validateCandidateScoreCardInput, validateCandidateStatus, validateId, ValidationError } from "./validation";
import { AuthorizationError } from "./itemFingerprintRepository";

interface RawCandidateMatchRow {
  id: string;
  foundReportId: string;
  itemId: string;
  vectorSimilarity: number | null;
  attributeScore: number;
  uniqueClueScore: number;
  locationScore: number;
  timeScore: number;
  overallScore: number;
  confidenceTier: string;
  status: string;
  evidence: string;
  createdAt: string;
  updatedAt: string;
}

function parseRow(row: RawCandidateMatchRow): CandidateScoreCard {
  return {
    id: row.id,
    foundReportId: row.foundReportId,
    itemId: row.itemId,
    vectorSimilarity: row.vectorSimilarity,
    attributeScore: row.attributeScore,
    uniqueClueScore: row.uniqueClueScore,
    locationScore: row.locationScore,
    timeScore: row.timeScore,
    overallScore: row.overallScore,
    confidenceTier: row.confidenceTier as CandidateScoreCard["confidenceTier"],
    status: row.status as CandidateScoreCard["status"],
    evidence: JSON.parse(row.evidence || "[]"),
    createdAt: row.createdAt,
    updatedAt: row.updatedAt,
  };
}

/**
 * Creates or updates a CandidateScoreCard.
 * Callable by trusted backend matching engine or staff.
 */
export async function createCandidateMatch(
  input: Partial<CandidateScoreCard>,
  isStaffOrSystem = true
): Promise<CandidateScoreCard> {
  if (!isStaffOrSystem) {
    throw new AuthorizationError("Only trusted system services can write candidate matches.");
  }

  const validated = validateCandidateScoreCardInput(input);

  // Validate existence of target report and item
  const found = await one<Report>("SELECT id, kind FROM reports WHERE id=?", validated.foundReportId);
  if (!found || found.kind !== "found") {
    throw new ValidationError(`Found report #${validated.foundReportId} does not exist.`);
  }

  const item = await one<ProtectedItem>("SELECT id FROM protected_items WHERE id=?", validated.itemId);
  if (!item) {
    throw new ValidationError(`Protected item #${validated.itemId} does not exist.`);
  }

  const candidateId = input.id ? validateId(input.id, "id") : `cand-${id("").slice(0, 16)}`;
  const timestamp = now();

  await transaction(async () => {
    await run(
      `INSERT INTO candidate_matches (
        id, "foundReportId", "itemId", "vectorSimilarity", "attributeScore",
        "uniqueClueScore", "locationScore", "timeScore", "overallScore",
        "confidenceTier", status, evidence, "createdAt", "updatedAt"
      ) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?)
      ON CONFLICT("foundReportId", "itemId") DO UPDATE SET
        "vectorSimilarity"=excluded."vectorSimilarity",
        "attributeScore"=excluded."attributeScore",
        "uniqueClueScore"=excluded."uniqueClueScore",
        "locationScore"=excluded."locationScore",
        "timeScore"=excluded."timeScore",
        "overallScore"=excluded."overallScore",
        "confidenceTier"=excluded."confidenceTier",
        status=excluded.status,
        evidence=excluded.evidence,
        "updatedAt"=excluded."updatedAt"`,
      candidateId,
      validated.foundReportId,
      validated.itemId,
      validated.vectorSimilarity ?? null,
      validated.attributeScore,
      validated.uniqueClueScore,
      validated.locationScore,
      validated.timeScore,
      validated.overallScore,
      validated.confidenceTier,
      validated.status,
      JSON.stringify(validated.evidence),
      timestamp,
      timestamp
    );
  });

  const saved = await one<RawCandidateMatchRow>(
    'SELECT * FROM candidate_matches WHERE "foundReportId"=? AND "itemId"=?',
    validated.foundReportId,
    validated.itemId
  );

  if (!saved) {
    throw new Error("Failed to retrieve saved candidate match.");
  }

  return parseRow(saved);
}

/**
 * Retrieves a candidate match by primary key.
 * Enforces that only the registered item owner or staff can inspect the scorecard.
 */
export async function getCandidateMatchById(
  idStr: string,
  requestingUserId?: string,
  isStaffOrSystem = false
): Promise<CandidateScoreCard | null> {
  const safeId = validateId(idStr, "candidate match ID");
  const row = await one<RawCandidateMatchRow>("SELECT * FROM candidate_matches WHERE id=?", safeId);
  if (!row) return null;

  if (!isStaffOrSystem) {
    if (!requestingUserId) {
      throw new AuthorizationError("Authentication required to view candidate scorecards.");
    }
    const item = await one<ProtectedItem>('SELECT "userId" FROM protected_items WHERE id=?', row.itemId);
    if (!item || item.userId !== requestingUserId) {
      throw new AuthorizationError("You do not have permission to view this candidate scorecard.");
    }
  }

  return parseRow(row);
}

/**
 * Lists all candidate matches for a given protected item.
 * Restricted to the item owner or staff.
 */
export async function listCandidatesForItem(
  itemId: string,
  requestingUserId?: string,
  isStaffOrSystem = false
): Promise<CandidateScoreCard[]> {
  const safeItemId = validateId(itemId, "itemId");

  if (!isStaffOrSystem) {
    if (!requestingUserId) {
      throw new AuthorizationError("Authentication required.");
    }
    const item = await one<ProtectedItem>('SELECT "userId" FROM protected_items WHERE id=?', safeItemId);
    if (!item || item.userId !== requestingUserId) {
      throw new AuthorizationError("You cannot view candidates for an item you do not own.");
    }
  }

  const rows = await all<RawCandidateMatchRow>(
    'SELECT * FROM candidate_matches WHERE "itemId"=? ORDER BY "overallScore" DESC',
    safeItemId
  );

  return rows.map(parseRow);
}

/**
 * Updates the candidate status (e.g. from 'candidate' to 'verification_required' or 'verified').
 */
export async function updateCandidateStatus(
  idStr: string,
  newStatus: CandidateScoreCard["status"],
  isStaffOrSystem = false
): Promise<CandidateScoreCard> {
  if (!isStaffOrSystem) {
    throw new AuthorizationError("Only verified staff or backend services can update candidate statuses.");
  }

  const safeId = validateId(idStr, "candidate match ID");
  const validatedStatus = validateCandidateStatus(newStatus);
  const timestamp = now();

  await run(
    'UPDATE candidate_matches SET status=?, "updatedAt"=? WHERE id=?',
    validatedStatus,
    timestamp,
    safeId
  );

  const updated = await one<RawCandidateMatchRow>("SELECT * FROM candidate_matches WHERE id=?", safeId);
  if (!updated) {
    throw new ValidationError(`Candidate match #${safeId} not found.`);
  }

  return parseRow(updated);
}
